### ISSUE TITLE
Copying/deleting folder with content may cause in folder-creation/deletion being missed

### ISSUE THREAD

**Issue by capi** [syncthing/syncthing-inotify#22] opened 2015-03-04 23:16 UTC
I just played around with `syncthing-inotify`. My use-case was to copy a folder with content via Samba to a Linux box, that uses `syncthing-inotify` to monitor a share.

Then log-output from `syncthing-inotify` was as follows:

    [OK] 2015/03/05 00:04:57 syncwatcher.go:407: Syncthing is indexing change in syncthing-test: syncthing-windows-386-v0.10.24/AUTHORS.txt
    [OK] 2015/03/05 00:04:57 syncwatcher.go:407: Syncthing is indexing change in syncthing-test: syncthing-windows-386-v0.10.24/FAQ.pdf
    [OK] 2015/03/05 00:04:57 syncwatcher.go:407: Syncthing is indexing change in syncthing-test: syncthing-windows-386-v0.10.24/Getting-Started.pdf
    [OK] 2015/03/05 00:04:57 syncwatcher.go:407: Syncthing is indexing change in syncthing-test: syncthing-windows-386-v0.10.24/LICENSE.txt
    [OK] 2015/03/05 00:04:57 syncwatcher.go:407: Syncthing is indexing change in syncthing-test: syncthing-windows-386-v0.10.24/README.txt
    [OK] 2015/03/05 00:04:58 syncwatcher.go:407: Syncthing is indexing change in syncthing-test: syncthing-windows-386-v0.10.24/syncthing.exe
    [OK] 2015/03/05 00:04:58 syncwatcher.go:407: Syncthing is indexing change in syncthing-test: syncthing-windows-386-v0.10.24/syncthing.exe.md5

As one can see, the initial creation of the parent directory is missing. This causes `syncthing` to hang and causes a warning, that the poller is hanging on the receiving end. This is due to `syncthing` not being able to open the parent directory for the file it wants to sync, as the directory itself was never added.

    [2ZPCV] 00:07:52 INFO: Puller (folder "syncthing-test", file "syncthing-windows-386-v0.10.24\\syncthing.exe"): dst stat dir:GetFileAttributesEx E:\Martin\Syncthing\Syncthing-Test\syncthing-windows-386-v0.10.24: The system cannot find the file specified.

When deleting the tree via Samba caused the parent directory to remain empty on the receiving side, as the directory removal has not been scheduled.

Both issues corrected themselves, when triggering a scan via `syncthing` Web-UI. I suppose, it would have also been enough to wait for the rescan interval of the folder. 

I am not entirely sure if this is an issue with `syncthing-inotify` or with `syncthing` core itself. Does `syncthing-inotify` schedule specific files/directories or the whole folder with all children?

**Comment by AudriusButkevicius** [comment] 2015-03-04 23:42
Very good detective work.

It seems that inotify needs to be aware whether or not we've indexed the directory to start with, otherwise it may break syncthing.

**Comment by capi** [comment] 2015-03-05 07:43
If I create the directory manually first, `syncthing-inotify` picks up directory creation just fine. There seems to be something odd when copying via Samba. Need to test if this also happens if I copy recursively from the shell.

**Comment by Zillode** [comment] 2015-03-05 13:08
Good catch, I think I've stumbled upon this bug before but couldn't reproduce it.
I think this should be fixed in Syncthing, no? I can also fix it here but you still would be able to let ST get into troubles easily.

**Comment by AudriusButkevicius** [comment] 2015-03-05 13:25
Yeah, I guess we should solve it in syncthing, in which case you could just notify us about exact files, and we would build up the directory tree from there if we are missing any intermediate pieces.

**Closed** 2015-03-09 07:22 UTC

**Comment by capi** [comment] 2015-04-27 19:49
Unfortunately I don't think that the issue is fixed (at least not under Windows using `syncthing-inotify-windows-amd64-v0.6.tar.gz`):

Steps to reproduce:
In an otherwise empty repository

    mkdir a
    mkdir a\b
    echo "Test" > a\b\test.txt

At this point, the output is:

    [OK] 21:40:42 Syncthing is indexing change in syncthing-test: [a]
    [OK] 21:40:45 Syncthing is indexing change in syncthing-test: [a\b]
    [OK] 21:40:53 Syncthing is indexing change in syncthing-test: [a\b\test.txt]

The Web-GUI reports 3 items in the index. Then do:
   rmdir /s a

The output now is:

    [OK] 21:42:29 Syncthing is indexing change in syncthing-test: [a\b\test.txt]

The index reports still two items being present (`a`, `a\b`). Only a refresh (or the timeout) will get rid of the now no longer existing directories.

What I can think of, are two things: either `syncthing` should not only walk up the tree until a known directory in the index is found, but also verify thall elements in the path still exist on disk.
or it maybe is simply a race condition, i.e. the scan on `a` starts while `a\b` still exists, because the recursive delete has only yet removed the file. So maybe an idea would be to add a delay of a few seconds before submitting a scan request for a directory after inotify triggered.

Also, looking at the output, it doesn't seem that deleting a directory seems to fire, only it's creation.

**Comment by AudriusButkevicius** [comment] 2015-04-27 19:53
I think the bug here is inotify not aggregating the events and not traversing up to the parent, which is suposed to be deleted too.

**Comment by Zillode** [comment] 2015-04-27 20:19
Thanks for your report @capi! It was a different bug so I copied your findings to https://github.com/syncthing/syncthing-inotify/issues/52 and fixed it.
