### ISSUE TITLE
-target is ignored when using -home ==> issue with 0.0.0.0:8384 ...

### ISSUE THREAD

**Issue by jcnoir** [syncthing/syncthing-inotify#157] opened 2017-02-26 12:26 UTC
If I set the syncthing GUI to listen on 0.0.0.0:8384 then syncthing-inotify (when configured with -home) cannot sniff the configuration and will try to connect to 127.0.0.1 even if I define the -target property correctly.

Is it possible not to ignore the -target command line parameter in this case ?

**Comment by calmh** [comment] 2017-02-26 14:27
127.0.0.1:8384 is the correct thing to connect to when Syncthing is listening on 0.0.0.0:8384 - is this not what's happening, or did you expect something else?

**Comment by jcnoir** [comment] 2017-02-26 14:39
It does try to connect to 127.0.0.1:8384.

My use case may be a bit non usual: I use docker:
 syncthing runs in a container (hostname=syncthing) and syncthing-inotify runs in an other container (hostname=syncthing-inotify). Both containers share the same home folder.

So even if my syncthing container binds on 0.0.0.0:8384, syncthing-inotify needs to connect to syncthing:8384 instead of 127.0.0.1:8384.
I expect that setting -target to "syncthing:8384" (with -home pointing to folder shared by both containers) would make syncthing-inotify actually connect to syncthing:8384.

I hope it is clear.

**Comment by AudriusButkevicius** [comment] 2017-02-26 14:43
You need to link the containers

**Comment by AudriusButkevicius** [comment] 2017-02-26 14:44
Anyway, this is not a bug but you misusing/misconfiguring containers, hence closing.

**Comment by AudriusButkevicius** [comment] 2017-02-26 14:46
Actually, no, you are right, it may need to allow to override the address with target, hence reopening.

**Comment by AudriusButkevicius** [comment] 2017-02-26 14:46
Zillode can close is target already overrides.

**Comment by jcnoir** [comment] 2017-02-26 14:56
My container are already linked and I checked that they can communicate.
I checked that syncthing-inotify works if I change the configuration from 0.0.0.0:8384 ==> syncthing:8384 but I lose the web access from other locations.

I did not understand the last message. Do you say that the current version already overrides the url in the config file with the one in -target ? This is not what I see in syncthing-inotify v0.8.5 (go1.7.5 linux-amd64) (with syncthing v0.14.23)

**Comment by AudriusButkevicius** [comment] 2017-02-26 15:06
Yes.

**Comment by jcnoir** [comment] 2017-02-26 15:09
OK... I forgot to say I really like Syncthing and use it on all my machines. Thank you all for the great work !

**Comment by Zillode** [comment] 2017-02-26 17:48
Use the `-target` `-cert` and `api-stdin` options. This is all what is needed to start inotify.

hf!

**Closed by Zillode** 2017-02-26 17:48 UTC

**Comment by jcnoir** [comment] 2017-02-26 21:48
It is the workaround I use for now but it is not very nice: You also have to give the different folders  to sync (-folders) and not to forget to change this when you share a new folder ...

**Comment by Zillode** [comment] 2017-02-26 21:49
`-folders` is optional

**Comment by jcnoir** [comment] 2017-02-26 21:52
I miss something: How syncthing-notify knows which folder to watch without "-folder" ? It just ask for the folder list  to the syncthing api ?

**Comment by Zillode** [comment] 2017-02-26 22:07
correct

**Comment by jcnoir** [comment] 2017-02-26 22:13
Thanks for the tips.

**Comment by Zillode** [comment] 2017-02-28 21:23
yw
